var DATA = [
      { id:0, label:"com.terradue.jcatalogue.client", link:"com/terradue/jcatalogue/client/package-summary.html", type:"package" },
      { id:1, label:"com.terradue.jcatalogue.client.Catalogue", link:"com/terradue/jcatalogue/client/Catalogue.html", type:"class" },
      { id:2, label:"com.terradue.jcatalogue.client.CatalogueClient", link:"com/terradue/jcatalogue/client/CatalogueClient.html", type:"class" },
      { id:3, label:"com.terradue.jcatalogue.client.CatalogueDescription", link:"com/terradue/jcatalogue/client/CatalogueDescription.html", type:"class" },
      { id:4, label:"com.terradue.jcatalogue.client.CatalogueEntity", link:"com/terradue/jcatalogue/client/CatalogueEntity.html", type:"class" },
      { id:5, label:"com.terradue.jcatalogue.client.DataSet", link:"com/terradue/jcatalogue/client/DataSet.html", type:"class" },
      { id:6, label:"com.terradue.jcatalogue.client.OpenSearchUrl", link:"com/terradue/jcatalogue/client/OpenSearchUrl.html", type:"class" },
      { id:7, label:"com.terradue.jcatalogue.client.Parameter", link:"com/terradue/jcatalogue/client/Parameter.html", type:"class" },
      { id:8, label:"com.terradue.jcatalogue.client.Serie", link:"com/terradue/jcatalogue/client/Serie.html", type:"class" },
      { id:9, label:"com.terradue.jcatalogue.client.download", link:"com/terradue/jcatalogue/client/download/package-summary.html", type:"package" },
      { id:10, label:"com.terradue.jcatalogue.client.download.DownloadHandler", link:"com/terradue/jcatalogue/client/download/DownloadHandler.html", type:"class" },
      { id:11, label:"com.terradue.jcatalogue.client.download.Downloader", link:"com/terradue/jcatalogue/client/download/Downloader.html", type:"class" },
      { id:12, label:"com.terradue.jcatalogue.client.download.HttpDownloader", link:"com/terradue/jcatalogue/client/download/HttpDownloader.html", type:"class" },
      { id:13, label:"com.terradue.jcatalogue.client.download.Protocol", link:"com/terradue/jcatalogue/client/download/Protocol.html", type:"class" },
      { id:14, label:"com.terradue.jcatalogue.client.geo", link:"com/terradue/jcatalogue/client/geo/package-summary.html", type:"package" },
      { id:15, label:"com.terradue.jcatalogue.client.geo.Box", link:"com/terradue/jcatalogue/client/geo/Box.html", type:"class" },
      { id:16, label:"com.terradue.jcatalogue.client.geo.GeoLocation", link:"com/terradue/jcatalogue/client/geo/GeoLocation.html", type:"class" },
      { id:17, label:"com.terradue.jcatalogue.client.geo.Line", link:"com/terradue/jcatalogue/client/geo/Line.html", type:"class" },
      { id:18, label:"com.terradue.jcatalogue.client.geo.Point", link:"com/terradue/jcatalogue/client/geo/Point.html", type:"class" },
      { id:19, label:"com.terradue.jcatalogue.client.geo.Polygon", link:"com/terradue/jcatalogue/client/geo/Polygon.html", type:"class" },
      { id:20, label:"com.terradue.jcatalogue.client.internal.converters", link:"com/terradue/jcatalogue/client/internal/converters/package-summary.html", type:"package" },
      { id:21, label:"com.terradue.jcatalogue.client.internal.converters.AtomDateConverter", link:"com/terradue/jcatalogue/client/internal/converters/AtomDateConverter.html", type:"class" },
      { id:22, label:"com.terradue.jcatalogue.client.internal.converters.CharsetConverter", link:"com/terradue/jcatalogue/client/internal/converters/CharsetConverter.html", type:"class" },
      { id:23, label:"com.terradue.jcatalogue.client.internal.converters.GeoConverter", link:"com/terradue/jcatalogue/client/internal/converters/GeoConverter.html", type:"class" },
      { id:24, label:"com.terradue.jcatalogue.client.internal.converters.LocaleConverter", link:"com/terradue/jcatalogue/client/internal/converters/LocaleConverter.html", type:"class" },
      { id:25, label:"com.terradue.jcatalogue.client.internal.digester", link:"com/terradue/jcatalogue/client/internal/digester/package-summary.html", type:"package" },
      { id:26, label:"com.terradue.jcatalogue.client.internal.digester.AtomRulesModule", link:"com/terradue/jcatalogue/client/internal/digester/AtomRulesModule.html", type:"class" },
      { id:27, label:"com.terradue.jcatalogue.client.internal.digester.DataSetRulesModule", link:"com/terradue/jcatalogue/client/internal/digester/DataSetRulesModule.html", type:"class" },
      { id:28, label:"com.terradue.jcatalogue.client.internal.digester.LinkedAtomEntityModule", link:"com/terradue/jcatalogue/client/internal/digester/LinkedAtomEntityModule.html", type:"class" },
      { id:29, label:"com.terradue.jcatalogue.client.internal.digester.OpenSearchModule", link:"com/terradue/jcatalogue/client/internal/digester/OpenSearchModule.html", type:"class" },
      { id:30, label:"com.terradue.jcatalogue.client.internal.digester.SingleDataSetRulesModule", link:"com/terradue/jcatalogue/client/internal/digester/SingleDataSetRulesModule.html", type:"class" }

    ];
